# Generated by Django 4.1.7 on 2023-03-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
