# Generated by Django 4.1.7 on 2023-04-01 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='percent',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
