# Generated by Django 4.1.7 on 2023-04-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='coupon',
            field=models.IntegerField(),
        ),
    ]
